#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# vsop.py
#
# VSOP Main
#
#
# -----------------------------------------------------------------------------

__author__  = "Adrien and Kevin"
__version__ = '1.0'

import sys
from vsop_lexer import VsopLexer

class Style:
    OK = '\033[92m'
    WARNING = '\x1b[93m'
    ERROR = '\033[91m'
    ENDC = '\x1b[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_token(tokens):
    for t in tokens:
        if(t.type == "type_identifier"):
            print(f"{t.lineno},{t.column},type-identifier,{t.value}")
        elif(t.type == "object_identifier"):
            print(f"{t.lineno},{t.column},object-identifier,{t.value}")
        elif(t.type == "integer_literal"):
            print(f"{t.lineno},{t.column},integer-literal,{t.value}")
        elif(t.type == "string_literal"):
            print(f"{t.lineno},{t.column},string-literal,{t.value}")
        elif(t.type == "lower_equal"):
            print(f"{t.lineno},{t.column},lower-equal,{t.value}")
        else:
            print(f"{t.lineno},{t.column},{t.type}")

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def print_error(errors,f):
    for er in errors:
        eprint(f,":",er.line,":",er.column,": lexical error:",er.description,sep="")

def main(argv):
    phase = 0
    files = []

    for arg in argv:
        if arg == '-h':
            print("vsop.py -lex <inputfile>")
            exit()
        elif arg in ("-lex", "--lexer"):
            phase = 1
        else:
            files.append(arg)

    if phase != 1:
        print(Style.WARNING + "The only available for now is the lexer"
            + Style.ENDC)
        print("vsop.py -lex <inputfile>")
        exit(1)
    if not files:
        print(Style.WARNING + "You must provide at least one file" + Style.ENDC)
        print("vsop.py -lex <inputfile>")
        exit(1)

    for f in files:
        with open(f, 'r') as file:
            input = file.read()

        # well... no other option for the moment so go lexer i choose you
        lexer = VsopLexer()
        tokens,errors = lexer.tokenize(input)
        print_error(errors,f)
        print_token(tokens)


if __name__ == "__main__":
    main(sys.argv[1:])
